// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faiavzyvcxoeydotrdqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhaWF2enl2Y3hvZXlkb3RyZHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNTY3OTQsImV4cCI6MjA1NTczMjc5NH0.tVtIavB4uzzd7cVWCqwGiTO5FAA5OOw0PmPtzC9AJLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);